import React from 'react';
import Head from 'next/head';
import styles from '../../styles/Layout.module.scss';
import Header from '../Interface/Header';
import { useRouter } from 'next/router';
import Loader from '../Loader/Loader';
import { useRecoilValue } from 'recoil';
import { authAtom } from '../../atom/authAtom';

type Props = {
  children: React.ReactNode;
};

const Layout = ({ children }: Props) => {
  const { pathname } = useRouter();
  const isLoading = useRecoilValue(authAtom).loading;
  return (
    <>
      <Head>
        <title>
          TicTacToe ||{' '}
          {pathname === '/'
            ? 'Home'
            : pathname === '/login'
            ? 'Login'
            : pathname === '/register'
            ? 'Register'
            : pathname === '/game'
            ? 'Game'
            : '404'}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.layout}>
        {isLoading && <Loader size={100} speed={1.4} color="#ffd700" />}
        <Header title="TicTacToe" />
        {children}
      </div>
    </>
  );
};

export default Layout;
